### ISSUE TITLE
Unable to Install

### ISSUE THREAD

**Issue by gauhar013** [TeamMetaxone/Cyberonix#63]
File "/home/muezza013/Cyberonix/cyberonix.py", line 5, in <module>
    from main import * 
    ^^^^^^^^^^^^^^^^^^
  File "/home/muezza013/Cyberonix/main/arguments.py", line 6, in <module>
    from ipwhois import IPWhois
ModuleNotFoundError: No module named 'ipwhois'

I am Getting this Error, Please tell me the solution to fix it.

**Comment by b14ckky** [comment]
Just install that package by using these commands: `pip install ipwhois` or `pip3 install ipwhois`.

**Comment by Raymond-Reddingtonjr** [comment]
Im having the same issue but with selenium. I have it installed its inside a virtual environment 

[+] Checking For Updates....
[+] It Is Updated
Traceback (most recent call last):
  File "/home/kali/OSINT_Tools/Cyberonix/Cyberonix/cyberonix.py", line 5, in <module>
    from main import * 
    ^^^^^^^^^^^^^^^^^^
  File "/home/kali/OSINT_Tools/Cyberonix/Cyberonix/main/arguments.py", line 5, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
Traceback (most recent call last):
  File "/home/kali/OSINT_Tools/Cyberonix/Cyberonix/cyberonix.py", line 5, in <module>
    from main import * 
    ^^^^^^^^^^^^^^^^^^
  File "/home/kali/OSINT_Tools/Cyberonix/Cyberonix/main/arguments.py", line 5, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'  

Does anyone or has anyone heard of a solution?

**Comment by Karanmaurya003** [comment]
██████ ██    ██ ██████  ███████ ██████   ██████  ███    ██ ██ ██   ██ 
        ██       ██  ██  ██   ██ ██      ██   ██ ██    ██ ████   ██ ██  ██ ██  
        ██        ████   ██████  █████   ██████  ██    ██ ██ ██  ██ ██   ███   
        ██         ██    ██   ██ ██      ██   ██ ██    ██ ██  ██ ██ ██  ██ ██  
        ██████    ██    ██████  ███████ ██   ██  ██████  ██   ████ ██ ██   ██ 
                                                                            v3.0
                    By Team Defronix

        
                A Complete Resource Hub For Cyber Security Community
--------------------------------------------------------------------------------
                                Setup Completed
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/karan/Desktop/Cyberonix/cyberonix.py", line 5, in <module>
    from main import * 
    ^^^^^^^^^^^^^^^^^^
  File "/home/karan/Desktop/Cyberonix/main/arguments.py", line 5, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
hey tried everyway possible in mind and i have also installed the selenium still it is reflecting this error repeatedly i think this is problem with the tool itself  please fix it as soon as possible
